import { useState } from 'react';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';

type ModalType = 'about' | 'contact' | 'disclaimer' | null;

export const Footer = () => {
  const [openModal, setOpenModal] = useState<ModalType>(null);

  const currentYear = new Date().getFullYear();

  return (
    <>
      <footer className="relative z-10 border-t border-primary/20 bg-card/30 backdrop-blur-sm mt-12">
        <div className="container mx-auto px-4 py-8">
          <div className="flex flex-col md:flex-row items-center justify-between gap-4">
            <p className="text-muted-foreground text-sm">
              © {currentYear} Virtualsite Pty Ltd. All rights reserved.
            </p>
            
            <nav className="flex items-center gap-6">
              <button
                onClick={() => setOpenModal('about')}
                className="text-sm text-muted-foreground hover:text-secondary transition-colors"
              >
                About
              </button>
              <button
                onClick={() => setOpenModal('contact')}
                className="text-sm text-muted-foreground hover:text-secondary transition-colors"
              >
                Contact
              </button>
              <button
                onClick={() => setOpenModal('disclaimer')}
                className="text-sm text-muted-foreground hover:text-secondary transition-colors"
              >
                Disclaimer
              </button>
            </nav>
          </div>
          
          <p className="text-center text-muted-foreground text-sm mt-4 font-display">
            🇿🇦 Made with ❤️ in Mzansi ⚽
          </p>
        </div>
      </footer>

      <Dialog open={openModal === 'about'} onOpenChange={() => setOpenModal(null)}>
        <DialogContent className="bg-card border-primary/30">
          <DialogHeader>
            <DialogTitle className="font-display text-secondary text-xl">About Us</DialogTitle>
          </DialogHeader>
          <div className="text-muted-foreground space-y-3">
            <p>
              PSL Match Predictor is an AI-powered soccer prediction platform designed for South African Premier Soccer League fans.
            </p>
            <p>
              Our machine learning models analyze historical match data, team performance, and various factors to provide match predictions.
            </p>
            <p className="text-sm">
              Developed by <span className="text-secondary font-semibold">Virtualsite Pty Ltd</span>
            </p>
          </div>
        </DialogContent>
      </Dialog>

      <Dialog open={openModal === 'contact'} onOpenChange={() => setOpenModal(null)}>
        <DialogContent className="bg-card border-primary/30">
          <DialogHeader>
            <DialogTitle className="font-display text-secondary text-xl">Contact Us</DialogTitle>
          </DialogHeader>
          <div className="text-muted-foreground space-y-3">
            <p>For inquiries, support, or feedback:</p>
            <p>
              <span className="text-foreground font-medium">Email:</span>{' '}
              <a href="mailto:info@virtualsite.co.za" className="text-secondary hover:underline">
                info@virtualsite.co.za
              </a>
            </p>
            <p>
              <span className="text-foreground font-medium">Company:</span> Virtualsite Pty Ltd
            </p>
            <p>
              <span className="text-foreground font-medium">Location:</span> South Africa
            </p>
          </div>
        </DialogContent>
      </Dialog>

      <Dialog open={openModal === 'disclaimer'} onOpenChange={() => setOpenModal(null)}>
        <DialogContent className="bg-card border-primary/30">
          <DialogHeader>
            <DialogTitle className="font-display text-secondary text-xl">Disclaimer</DialogTitle>
          </DialogHeader>
          <div className="text-muted-foreground space-y-3 text-sm">
            <p>
              <strong className="text-foreground">For Entertainment Purposes Only:</strong> The predictions provided by this platform are generated by AI models and are intended for entertainment purposes only.
            </p>
            <p>
              <strong className="text-foreground">No Gambling Advice:</strong> This platform does not encourage or promote gambling. Predictions should not be used as the basis for any betting or wagering activities.
            </p>
            <p>
              <strong className="text-foreground">No Guarantee:</strong> We do not guarantee the accuracy of any predictions. Soccer matches are inherently unpredictable, and results may vary significantly from predictions.
            </p>
            <p>
              <strong className="text-foreground">Liability:</strong> Virtualsite Pty Ltd accepts no liability for any losses or damages arising from the use of this platform or reliance on its predictions.
            </p>
          </div>
        </DialogContent>
      </Dialog>
    </>
  );
};
